### ISSUE TITLE
s3deploy not attaching event

### ISSUE THREAD

**Issue by Wabba2** [matt-filion/serverless-external-s3-event#23]
Hi there,

maybe I'm missing something, but when I run "sls s3deploy", it just returns after a few seconds without any input (it's supposed to return _Attaching event(s) to: BUCKET_NAME_)

```
service: ProcessUploadedTraceFiles

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
      Resource: "arn:aws:dynamodb:eu-central-1:<account_no>:table/<table_name>"
    - Effect: "Allow"
      Action:
        - "s3:PutBucketNotification"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::<bucket>"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource: "arn:aws:s3:::<bucket>/*"

functions:
  processUploadedTraceFiles:
    handler: handler.processMetadata
    memorySize: 128
    events:
      - existingS3:
          bucket: <bucket>
          events: 
            - s3:ObjectCreated:*

plugins:
  - serverless-offline
  - serverless-external-s3-event
```

Serverless: 1.15.3
serverless-external-s3-event: 2.0

Any help is appreciated.

Thanks,
Daniel
