### ISSUE TITLE
SyntaxError: Unexpected token this

### ISSUE THREAD

**Issue by craigmonson** [matt-filion/serverless-external-s3-event#24]
Node Version: 8.1.0
Serverless Version: 1.17.0
serverless-external-s3-event: 2.0 branch (HEAD)

Running in the node:8.1.0-alpine container

```
%> docker run -itP -v ... -v ... -e SLS_DEBUG=true serverless-test deploy

  Syntax Error -------------------------------------------

  Unexpected token this

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

SyntaxError: Unexpected token this
/node_modules/serverless-plugin-existing-s3/Transformer.js:6
  constructor(this.lambdaPermissions){
              ^^^^

SyntaxError: Unexpected token this
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/serverless-plugin-existing-s3/index.js:5:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at plugins.forEach (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:65:22)
    at Array.forEach (native)
    at PluginManager.loadPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:64:13)
    at PluginManager.loadServicePlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:91:10)
    at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:60:10)
    at service.load.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:72:28)
    at <anonymous>
From previous event:
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at __dirname (/usr/local/lib/node_modules/serverless/bin/serverless:20:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:36:4)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.1.0
     Serverless Version:     1.17.0
```

serverless.yaml:
```

service: "blahblah-decider"

custom:
  devBucket: "blahblah-config-log-dev"
  prodBucket: "blahblah-config-log"
  bucketValue: "${self:custom.${opt:stage, self:provider.stage}Bucket}"

plugins:
  - serverless-plugin-existing-s3

provider:
  name: "aws"
  runtime: "python2.7"
  stage: "dev"
  region: "us-west-2"
  versionFunctions: false
  stackTags:
    DeploymentMethod: "Serverless - blahblah-decider"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:ListBucket
      Resource: arn:aws:s3:::${self:custom.bucketValue}

functions:
  decide:
    handler: handler.Decide
    events:
      - existingS3:
          bucket: ${self:custom.bucketValue}
          events:
            - s3:ObjectCreated:*

resources:
  Resources:
  Outputs:
    bucketValue:
      Description: "bucketValue"
      Value: ${self:custom.bucketValue}
```
