### ISSUE TITLE
Is not possible to have multiple externalS3 events...

### ISSUE THREAD

**Issue by AndrewFarley** [matt-filion/serverless-external-s3-event#36]
It is not possible (currently) to have multiple externalS3 events...

eg:

```
events:
  - existingS3:
      bucket: sample-bucket-name
      event: s3:ObjectCreated:*
      rules:
        - prefix: 'media/'
        - suffix: '.jpg'
  - existingS3:
      bucket: sample-bucket-name
      event: s3:ObjectCreated:*
      rules:
        - prefix: 'media/'
        - suffix: '.png'
```
