### ISSUE TITLE
Plugin believes functions haven't been deployed, when in fact they have

### ISSUE THREAD

**Issue by mrcrilly** [matt-filion/serverless-external-s3-event#37]
**tl;dr**

I am unable to get this plugin to work as it cannot correctly identify that my functions have been deployed. The error from the plugin is as follows:

```
It looks like the function has not yet been deployed. You must use 'sls deploy' before doing 'sls s3deploy.
```

(there's an apostrophe missing from the end of that error message, by the way.)

The functions have indeed been deployed and exist, and work fine. The S3 buckets exist also, hence the need to use this plugin. After doing some debugging, I noticed the following issue at line `160` of `index.js` when it compares the deployed name versus the ARN name:

```
Serverless: ukrgdatapipeline-dev-ukrgdatapipeline versus ukrgdatapipeline-dev-UkRgDataPipeline
Serverless: ukrgdatapipeline-dev-RgToDocker versus ukrgdatapipeline-dev-UkRgDataPipeline
```

I've provided details at the bottom about my changes to produce this output.

It seems to only work with comparing one of the functions to all of the rest of them. That is, `ukrgdatapipeline-dev-UkRgDataPipeline` is the deployed name and it's used to compare against the ARNs of two functions to ensure they're deployed:

- `ukrgdatapipeline-dev-ukrgdatapipeline`
- `ukrgdatapipeline-dev-RgToDocker`

Either that or it's simply short circuiting.

Anyway it's not comparing the two correctly, and I'm unsure why until I do some further work.

Thoughts? More information provided below.

Version information:
Node.js: 8.60
Serverless: 1.23.0
serverless-plugin-existing-s3: 2.0.3

Here is my yaml template:

```
service:
  name: ukrgdatapipeline

plugins:
  - serverless-python-requirements
  - serverless-external-s3-event

provider:
  name: aws
  region: ap-southeast-2
  runtime: python2.7
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::${self:custom.UkDataS3Bucket}-${opt:stage}"
    - Effect: "Allow"
      Action:
        - "kms:*"
      Resource:
        - ${env:AWS_KMS_KEY_ARN}

custom:
  bamboo:
    project_id: ${env:BAMBOO_DEPLOYMENT_PROJECT_ID}
    environment_id: ${env:BAMBOO_DEPLOYMENT_ENVIRONMENT_ID}
    release_id: ${env:BAMBOO_DEPLOYMENT_RELEASE_ID}
  pythonRequirements:
      dockerizePip: true  
  ignoreme: ignoreme
functions:
  ukrgdatapipeline:
    name: <ignore me>
    runtime: <ignore me>
    memorysize: 512
    timeout: 240
    package:
      artifact: <ignore me>
    handler: <ignore me>
    description: Ignore Me
    environment:
      ETC: ETC
    events:
      - existingS3:
          bucket: ${self:custom.UkDataS3Bucket}-${opt:stage}
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: RouteingGuide/
            - suffix: .ZIP
  
  RgToDocker:
    name: ${self:service}-${opt:stage}-RgToDocker
    description: <ignore me>
    handler: <ignore me>
    runtime: python2.7
    environment:
      ETC: ETC
    events:
      - existingS3:
          bucket: ${self:custom.ProcessedUkDataS3Bucket}-${opt:stage}
          event: s3:ObjectCreated:*
          rules:
            - prefix: RouteingGuideData/
```

SLS_DEBUG message:

```
Serverless: Invoke aws:info
Service Information
service: ukrgdatapipeline
stage: dev
region: ap-southeast-2
stack: ukrgdatapipeline-dev
api keys:
  None
endpoints:
  None
functions:
  ukrgdatapipeline: ukrgdatapipeline-dev-ukrgdatapipeline
  RgToDocker: ukrgdatapipeline-dev-RgToDocker
Serverless: ukrgdatapipeline-dev-ukrgdatapipeline versus ukrgdatapipeline-dev-UkRgDataPipeline
Serverless: ukrgdatapipeline-dev-RgToDocker versus ukrgdatapipeline-dev-UkRgDataPipeline

  Error --------------------------------------------------

  It looks like the function has not yet been deployed. You must use 'sls deploy' before doing 'sls s3deploy.

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: It looks like the function has not yet been deployed. You must use 'sls deploy' before doing 'sls s3deploy.
    at S3Deploy.getLambdaFunctionConfigurationFromDeployedStack (/Users/crilly/git/uk-rg-data-pipeline/deployment/serverless/node_modules/serverless-external-s3-event/index.js:166:13)
    at bucket.NotificationConfiguration.LambdaFunctionConfigurations.forEach (/Users/crilly/git/uk-rg-data-pipeline/deployment/serverless/node_modules/serverless-external-s3-event/index.js:232:36)
    at Array.forEach (<anonymous>)
    at bucketNotifications.forEach (/Users/crilly/git/uk-rg-data-pipeline/deployment/serverless/node_modules/serverless-external-s3-event/index.js:231:71)
    at Array.forEach (<anonymous>)
    at info.getStackInfo.then (/Users/crilly/git/uk-rg-data-pipeline/deployment/serverless/node_modules/serverless-external-s3-event/index.js:228:27)
From previous event:
    at S3Deploy.afterS3DeployFunctions (/Users/crilly/git/uk-rg-data-pipeline/deployment/serverless/node_modules/serverless-external-s3-event/index.js:222:32)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:39:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.6.0
     Serverless Version:     1.23.0

...

Serverless: Invoke s3deploy
Serverless: ukrgdatapipeline-dev-ukrgdatapipeline versus ukrgdatapipeline-dev-UkRgDataPipeline
Serverless: ukrgdatapipeline-dev-RgToDocker versus ukrgdatapipeline-dev-UkRgDataPipeline

  Error --------------------------------------------------

  It looks like the function has not yet been deployed. You must use 'sls deploy' before doing 'sls s3deploy.

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: It looks like the function has not yet been deployed. You must use 'sls deploy' before doing 'sls s3deploy.
    at S3Deploy.getLambdaFunctionConfigurationFromDeployedStack (/Users/crilly/git/uk-rg-data-pipeline/deployment/serverless/node_modules/serverless-external-s3-event/index.js:166:13)
    at bucket.NotificationConfiguration.LambdaFunctionConfigurations.forEach (/Users/crilly/git/uk-rg-data-pipeline/deployment/serverless/node_modules/serverless-external-s3-event/index.js:232:36)
    at Array.forEach (<anonymous>)
    at bucketNotifications.forEach (/Users/crilly/git/uk-rg-data-pipeline/deployment/serverless/node_modules/serverless-external-s3-event/index.js:231:71)
    at Array.forEach (<anonymous>)
    at info.getStackInfo.then (/Users/crilly/git/uk-rg-data-pipeline/deployment/serverless/node_modules/serverless-external-s3-event/index.js:228:27)
From previous event:
    at S3Deploy.afterS3DeployFunctions (/Users/crilly/git/uk-rg-data-pipeline/deployment/serverless/node_modules/serverless-external-s3-event/index.js:222:32)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:39:50)
    at <anonymous>

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.6.0
     Serverless Version:     1.23.0
```

I added the following lines to `index.js` (line: `160`) to get some additional information about what's going on here:

**Original**:

```
let deployed = results.functions.find((fn) => fn.deployedName === cfg.LambdaFunctionArn);
```

**Edited**:

```
let deployed = results.functions.find((fn) => {
    this.serverless.cli.log(fn.deployedName + ' versus ' + cfg.LambdaFunctionArn);
    fn.deployedName === cfg.LambdaFunctionArn;
});
```

Which produces the following output, which can be seen above mixed into the console text:

```
Serverless: ukrgdatapipeline-dev-ukrgdatapipeline versus ukrgdatapipeline-dev-UkRgDataPipeline
Serverless: ukrgdatapipeline-dev-RgToDocker versus ukrgdatapipeline-dev-UkRgDataPipeline
```

**Comment by mrcrilly** [comment]
It seems to me as though the plugin can't handle a use case where multiple functions are being used and triggered on existing S3 buckets. In my case, each function need to trigger based on a separate, existing S3 bucket.

For the record, I've tried using `.toLowerCase()` to make the cases match, but the problem persists because it attempts to match the second function against the ARN of the first.

I'm still working on this for now.

**Comment by mrcrilly** [comment]
I was wrong about the plugin not being able to handle multiple functions. The problem seems to be here:

```
let deployed = results.functions.find((fn) => {
        this.serverless.cli.log(fn.deployedName + ' versus ' + cfg.LambdaFunctionArn);
        fn.deployedName === cfg.LambdaFunctionArn;
    });
```

(The `cli.log()` call was added by me to debug the situation.)

This call to `.find()` on the array isn't short circuiting when it finds a match:

```
Serverless: ukrgdatapipeline-dev-ukrgdatapipeline versus ukrgdatapipeline-dev-ukrgdatapipeline
Serverless: ukrgdatapipeline-dev-rgtodocker versus ukrgdatapipeline-dev-ukrgdatapipeline
```

It could be that there are difference in those string I can't see, such as invisible characters, but I doubt it, or something else is going on here.

**Comment by mrcrilly** [comment]
Aaand bingo. I've found the issue. Essentially it boils down to this: the name of the function as a key in the `functions` dictionary can't be different in any way to the name of the function via the `name` attribute. Example:

```
functions:
  testing01:
    name: Testing01
  
  testing02:
    name: testing02
```

Our testing01 function would cause the plugin to not see it has been deployed.

I'm not sure if this is a bug at this stage, or an error on my part. Should we be able to name the functions differently to their respective parent keys, or am I asking to eat my cake too? :-)
