### ISSUE TITLE
sis s3deploy always fail the first time

### ISSUE THREAD

**Issue by cscetbon** [matt-filion/serverless-external-s3-event#38]
version : 2.0.3

I need to run `sls s3deploy` twice because it always fail the first time with the error :
```
policyId exS3-v2-.....

  Type Error ---------------------------------------------

  Cannot read property 'Statement' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     ....

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.5.0
     Serverless Version:     1.23.0
```

Then the second time :
```
Serverless: beforeFunctions --> building ...
Serverless: beforeFunctions <-- Complete, built 2 events.
Serverless: functions --> prepare to be executed by s3 buckets ...
policyId exS3-v2-...
policyId exS3-v2-...
Serverless: functions <-- built 0 events across 1 buckets.
Serverless: beforeS3 -->
Serverless: beforeS3 <--
Serverless: s3 --> initiate requests ...
Serverless: s3 <-- Complete 0 updates.
```

Last information, I have 2 events on the same bucket with 2 different rules 

```
functions:
  f1:
    handler: handler.f1
    events:
      - existingS3:
          bucket: ${self:custom.bucketname}
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: /a/b/c/c1/
            - suffix: .csv
      - existingS3:
          bucket: ${self:custom.bucketname}
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: /a/b/c/c2/
            - suffix: .csv
```

**Comment by cscetbon** [comment]
I have now another issue. I have 5 events and now the plugin deploys 4 events then 1 event in turns, by turns.

```
$ sls s3deploy --stage demo|egrep 'LambdaFunctionArn|Serverless'
Serverless: beforeFunctions --> building ...
Serverless: beforeFunctions <-- Complete, built 5 events.
Serverless: functions --> prepare to be executed by s3 buckets ...
Serverless: functions <-- built 0 events across 1 buckets.
Serverless: beforeS3 -->
Serverless: beforeS3 <--
Serverless: s3 --> initiate requests ...
                "LambdaFunctionArn": "arn:aws:lambda:us-east-1:xxxxxxxxxxx:function:my-project",
Serverless: s3 <-- Complete 1 updates.
$ sls s3deploy --stage demo|egrep 'LambdaFunctionArn|Serverless' 
Serverless: beforeFunctions --> building ...
Serverless: beforeFunctions <-- Complete, built 5 events.
Serverless: functions --> prepare to be executed by s3 buckets ...
Serverless: functions <-- built 0 events across 1 buckets.
Serverless: beforeS3 -->
Serverless: beforeS3 <--
Serverless: s3 --> initiate requests ...
                "LambdaFunctionArn": "arn:aws:lambda:us-east-1:xxxxxxxxxxx:function:my-project",
                "LambdaFunctionArn": "arn:aws:lambda:us-east-1:xxxxxxxxxxx:function:my-project",
                "LambdaFunctionArn": "arn:aws:lambda:us-east-1:xxxxxxxxxxx:function:my-project",
                "LambdaFunctionArn": "arn:aws:lambda:us-east-1:xxxxxxxxxxx:function:my-project",
Serverless: s3 <-- Complete 1 updates.
```

**Comment by nbk11kk** [comment]
@cscetbon when I follow the procedure no events are getting created.Any clue why??

```
plugins:
  - serverless-plugin-existing-s3

functions:
  ETL:
    handler: TP_S3_to_Redshift.lambda_handler
    name: TerminologyPortalETLKK-dev-ETL
    package:
      artifact: ETL/artifacts/ETL.zip
    events:
      - existings3:
          bucket: imo-bi
          events: 
            - s3:ObjectCreated:*
          rules:
            - prefix: log/LAMBDA_INVOKE_TEST/

```


```
Serverless: Invoke s3deploy
Serverless: beforeFunctions --> building ...
Serverless: beforeFunctions <-- Complete, built 0 events.
Serverless: functions --> prepare to be executed by s3 buckets ...
Serverless: functions <-- built 0 events across 0 buckets.
Serverless: beforeS3 -->
Serverless: beforeS3 <--
```

**Comment by cscetbon** [comment]
@nbk11kk sorry but I don't see anything weird in your code ...

**Comment by nbk11kk** [comment]
In my actual prefix,I have spaces in the folder name.Removing spaces in S3 folder name worked.

**Comment by cscetbon** [comment]
Oh, that's why I didn't see anything weird. Cool !

**Comment by rschick** [comment]
I was able to reproduce this with plugin `2.2.0` and serverless `1.26.1`.  I've submitted a PR to fix it: #57

**Comment by cscetbon** [comment]
@rschick Do you think your patch fixes both issues I met ? https://github.com/matt-filion/serverless-external-s3-event/issues/38#issue-262299435 and https://github.com/matt-filion/serverless-external-s3-event/issues/38#issuecomment-347426420

**Comment by rschick** [comment]
@cscetbon I haven't tested with multiple events, do you have time to test it? As far as I know, the fix only addresses the first error "Cannot read property 'Statement' of undefined".

**Comment by cscetbon** [comment]
@rschick unfortunately I don't at the moment. I'll try to update that issue if I meet again. Thanks

**Comment by saffrydaffry** [comment]
@nbk11kk were you able to find what caused your issue? I'm also seeing the same output you posted... it's perplexing as there's no error, but in the UI you can see the S3 trigger is still not set up.
```  
plugins:
  - serverless-python-requirements
  - serverless-plugin-warmup
  - serverless-plugin-existing-s3 #sls s3deploy

functions:
  loader:
    handler: loader/loader.load
    role: arn:aws:iam::<stuff>
    events:
      - existingS3:
        bucket: <test-bucket>
        events:
          - s3:ObjectCreated:*
        rules:
          - prefix: 3/
          - suffix: .csv
```
```sls -version
1.27.0
~$ sls s3deploy
Serverless: beforeFunctions --> building ...
Serverless: beforeFunctions <-- Complete, built 0 events.
Serverless: functions --> prepare to be executed by s3 buckets ...
Serverless: functions <-- built 0 events across 0 buckets.
Serverless: beforeS3 -->
Serverless: beforeS3 <--
```
