### ISSUE TITLE
Duplicate entry under function triggers 

### ISSUE THREAD

**Issue by ajshukury** [matt-filion/serverless-external-s3-event#39]
When adding multiple buckets events like this:
```
 events:
      - existingS3:
          bucket: bucket1
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: prefiex1/
            - suffix: _raw.jpg    
      - existingS3:
          bucket: bucket1
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: prefiex2/
            - suffix: _raw.jpg   
```
after deployment I see 4 records under function triggers:
![image](https://user-images.githubusercontent.com/14077606/31278986-36ab7856-aa75-11e7-9355-d4fbc819d863.png)
