### ISSUE TITLE
multiple events overwrite existing config

### ISSUE THREAD

**Issue by twehrmann** [matt-filion/serverless-external-s3-event#46]
Hi,
I just want to register 2+ events using different rules to fire lambda. The plugin just creates one event and overwrite it after s3deploying . Used configuration is: 
```      
- existingS3:
          bucket: eoss-ordering
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: eoss_product_s2l1/
            - suffix: .zip
      - existingS3:
          bucket: eoss-ordering
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: eoss_product_s2fire/
            - suffix: .zip
```
Plugin should register multiple events if configured. Maybe it is possible to achieve this goal with multiple rules, too.

best wishes
