### ISSUE TITLE
'prefixes are overlapping for the same event type' error with different event types

### ISSUE THREAD

**Issue by kwhumphreys** [matt-filion/serverless-external-s3-event#53]
defining separate events (ObjectCreated/ObjectRemoved) for the same suffix gives:
`Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.`

```
functions:
  upload:
    handler: src/handler.upload
    events:
      - existingS3:
          bucket: BUCKET
          events:
            - s3:ObjectCreated:*
          rules:
            - suffix: .json
  remove:
    handler: src/handler.remove
    events:
      - existingS3:
          bucket: BUCKET
          events:
            - s3:ObjectRemoved:*
          rules:
            - suffix: .json
```

**Comment by kwhumphreys** [comment]
actually I get the same error with a single event:
```
functions:
  upload:
    handler: src/handler.upload
    events:
      - existingS3:
          bucket: BUCKET
          events:
            - s3:ObjectCreated:*
```
