### ISSUE TITLE
Triggers not getting created

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [matt-filion/serverless-external-s3-event#58]
I see that there are multiple issues relating to this, but none contained a satisfactory solution;

Here is my config;

```yaml
service: my-service
plugins:
  - serverless-plugin-existing-s3

custom:
  myBucket: my-bucket

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  memorySize: 128
  environment:
    DB_TABLE: { "Ref": "SomeDBTable" }
    SOME_CONFIG: ${ssm:someConfig}
    SOME_OTHER_CONFIG: ${ssm:someOtherConfig}
    AWS_ACCOUNT_ID: {"Ref": "AWS::AccountId"}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - { "Fn::GetAtt": ["SomeDBTable", "Arn" ] }
    -  Effect: "Allow"
       Action:
         - "s3:PutBucketNotification"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::${self:custom.myBucket}"

functions:
  myHandler:
    handler: handler.myHandler
    events:
      - existingS3:
        bucket: my-bucket
        events:
          - s3:ObjectCreated:*
  myHandlerTwo:
    handler: handler.myHandler
    events:
      - existingS3:
        bucket: my-bucket
        events:
          - s3:ObjectCreated:*
        rules:
          - suffix: .extension

resources:
 Resources:
  SomeDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: username
            AttributeType: S
        KeySchema:
          -
            AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
 Outputs:
    NewOutput:
      Description: "Description for the output"
      Value: "Some output value"

```

This results in everything I expect, except for a trigger. There is no triggers at all. What am I doing wrong?

---

Using: 
- serverless-plugin-existing-s3 version 2.2.1
- serverless version 1.27.3

**Comment by stephan-nordnes-eriksen** [comment]
Output of `sls s3deploy`:

```
Serverless: beforeFunctions --> building ...
Serverless: beforeFunctions <-- Complete, built 0 events.
Serverless: functions --> prepare to be executed by s3 buckets ...
Serverless: functions <-- built 0 events across 0 buckets.
Serverless: beforeS3 -->
Serverless: beforeS3 <--
```

**Comment by stephan-nordnes-eriksen** [comment]
So, this might be a config indentation-issue.

I recently re-tried this with the following syntax, and then it worked;


```yaml
functions:
  myHandler:
    handler: handler.myHandler
    events:
      - existingS3:
          bucket: my-bucket
          events:
            - s3:ObjectCreated:*
  myHandlerTwo:
    handler: handler.myHandler
    events:
      - existingS3:
          bucket: my-bucket
          events:
            - s3:ObjectCreated:*
          rules:
            - suffix: .extension
```

I also did some other changes, but I suspect this minor change is what made it work.
