### ISSUE TITLE
Event not created

### ISSUE THREAD

**Issue by mmplisskin** [matt-filion/serverless-external-s3-event#63]
```
iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "s3:*"
    Resource:
      Fn::Join:
        - ""
        - - ${self:custom.base_bucket_arn}

functions:
  convertToPdf:
    handler: handler.convertToPdf
    events:
      - existingS3:
          bucket:  ${self:custom.base_bucket}
          events:
            - s3:ObjectCreated:*

```

Not seeing any event on s3 or in cloudformation. No errors on deploy with verbose, region is hardcoded to the same region as s3 bucket

**Comment by mmplisskin** [comment]
runtime: nodejs8.10

"serverless-plugin-existing-s3": "^2.2.2"

**Comment by ashish8833** [comment]
I am facing the same issue.
Serverless Version :  1.26.1

**IAM ROLE**

```
iamRoleStatements:
   - Effect: Allow
      Action:
         - "s3:*"
      Resource: BUCKET-ARN
```

**Function Declaration**
```
functions:
      songUploadS3:
    handler: songs.songUploadS3
    events:
     - existingS3:
         bucket: BUCKET_NAME
         events:
           - s3:ObjectCreated:*
         rules:
           - prefix: orignal/
```

**Comment by saffrydaffry** [comment]
has anyone tested if this works with non-node.js runtimes? e.g. python3.6? I can't seem to get it to set up a trigger and I'm not getting any errors.

**Comment by dgoradia** [comment]
@saffrydaffry working for me with Golang runtime.

**Comment by cuantico** [comment]
One issue I saw is that I had to use a static value in the bucket name.

**Comment by oba11** [comment]
> has anyone tested if this works with non-node.js runtimes? e.g. python3.6? I can't seem to get it to set up a trigger and I'm not getting any errors.

Doesn't with python 3.6, had to write a custom resource to apply the bucket notification. Something like below

```
functions:
  PutBucketNotification:
    handler: custom/put_s3_notification.handler
  S3Watcher:
    handler: s3_watcher.handler
    environment:
      BUCKET_NAME: example-bucket

resources:
  Resources:
    PutBucketNotification:
      Type: Custom::PutBucketNotification
      Properties:
        LambdaArn:
          Fn::GetAtt: [S3WatcherLambdaFunction, Arn]
        Bucket: example-bucket
        ServiceToken:
          Fn::GetAtt: [PutBucketNotificationLambdaFunction, Arn]
    LambdaInvoke:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Fn::GetAtt: [S3WatcherLambdaFunction, Arn]
        Action: lambda:InvokeFunction
        Principal: s3.amazonaws.com
        SourceArn: arn:aws:s3:::example-bucket
```

With this, u dont even need to do `sls s3deploy`

**Comment by matt-filion** [comment]
Stale issue.

**Comment by mmplisskin** [comment]
@matt-filion This is still very relevant.

**Comment by matt-filion** [comment]
Can you provide some more details around the use case? Serverless.yaml, permissions, etc.

**Comment by chung2014** [comment]
I cannot have my existing s3 bucket to trigger a event to invoke the lambda function neither after I run `sls deploy`.

Even I put some files into my bucket `my0407test001log`, I don't get my lambda from running.

Here is my serverless.yaml attached.
```
service: my0407test001

plugins:
  serverless-plugin-existing-s3

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "s3:PutBucketNotification"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::my0407test001log"

functions:
  hello:
    handler: handler.hello
    events:
      - existingS3:
          bucket: my0407test001log
          events:
            - s3:ObjectCreated:*
          

```

**Comment by prasadbiarca** [comment]
I am also trying to use `existings3` function to use the already created `S3` bucket. When a file uploaded to my `S3 bucket`, event triggers `Serverless`. But my `Serverless` function failing to execute as it says `already exists`(using -`serverless-plugin-existing-s3` plugin). Below is my code:
```
service: test-serverless
provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: Allow
      Action:
       - s3:Put*
       - s3:Get*
      Resource: "arn:aws:s3:::test_bucket/*"
functions:
  test-serverless:
    handler: handler.lambda_handler
    events:
      - existingS3:
          bucket: test_bucket
          events: 
            - s3:ObjectCreated:*
          rules:
            - suffix: -testing.log
plugins:
   - serverless-python-requirements
   - serverless-plugin-existing-s3 plugin
custom:
  pythonRequirements:
     dockerizePip: non-linux
```
Function is not working as it sounds. Any help..!!!???
