### ISSUE TITLE
eventTypes.join is not a function

### ISSUE THREAD

**Issue by a1anw2** [matt-filion/serverless-external-s3-event#64]
Love the promise of this plugin; except i can't get it to work, no matter what combinations I throw at it.

Here is the serverless.yml snippet:

```
iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutBucketNotification"
      Resource: "arn:aws:s3:::${self:provider.stage}.files.mybucket"

  s3-upload:
    handler: event/s3.upload
    events:
      - existingS3:
          bucket: ${self:provider.stage}.files.mybucket
          events: s3:ObjectCreated:*
          rules:
            - prefix: client/
```

And the output:

```
devusermg@dev-virtualbox-2018:~/wc/api$ sls s3deploy
Serverless: beforeFunctions --> building ... 
Serverless: beforeFunctions <-- Complete, built 1 events.
Serverless: functions --> prepare to be executed by s3 buckets ... 
policyId exS3-v2-api-dev-s3-upload-devfilesmybucket
Serverless: functions <-- built 0 events across 1 buckets. 
Serverless: beforeS3 --> 
Serverless: beforeS3 <-- 
Serverless: s3 --> initiate requests ...
 
  Type Error ---------------------------------------------
 
  eventTypes.join is not a function
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.29.2
```
Version: serverless-plugin-existing-s3 : 2.2.2
