### ISSUE TITLE
Access denied to a s3 bucket in a different aws account

### ISSUE THREAD

**Issue by cpvandehey** [matt-filion/serverless-external-s3-event#75]
Hello,
When I try to use an existing s3 bucket that my aws account has access to (but the bucket lives in a different aws account), I get access denied despite my aws account having access to it.

I can prove this by creating a user from my account and trying to access the previously mentioned bucket. The user has access to the bucket. This does not occur when serverless creates users. I have even set up the serverless.yml config file to have access to all available buckets.

The bucket in the foreign account grants permissions to my account using the account ID.

```
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "*"
```
