### ISSUE TITLE
Trigger is Not Created 

### ISSUE THREAD

**Issue by shay-sundaysky** [matt-filion/serverless-external-s3-event#78]
I'm trying to deploy a java runtime lambda function with an S3 ObjectCreated trigger on a specific bucket. The deployment completes but no trigger is created when viewing the lambda function in the aws console.

Here's my config:
service: my-service

```
custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: java8
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action:
        - "s3:GetObject"
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::${file(env.yml):${self:custom.stage}.bucket}/*"
        - "arn:aws:s3:::${file(env.yml):${self:custom.stage}.bucket}"
    - Effect: Allow
      Action:
        - "s3:PutBucketNotification"
      Resource:
        - "arn:aws:s3:::${file(env.yml):${self:custom.stage}.bucket}"
  deploymentBucket:  ${file(env.yml):${self:custom.stage}.deploymentBucket}

plugins:
  - serverless-plugin-existing-s3

package:
  artifact:  my-service-${env:my-service_build_number}.zip

functions:
  objectArrived:
    handler: com.sundaysky.emr.lambda.LambdaFunctionHandler
    events:
      - existingS3:
          bucket: ${file(env.yml):${self:custom.stage}.bucket}
          event: s3:ObjectCreated:*
```
Using:
serverless@1.36.3
serverless-plugin-existing-s3@2.3.0

Again- trigger is not created to the lambda with the above configuration. Any idea why?
