### ISSUE TITLE
Use same configuration keys as in Serverless to avoid confusion

### ISSUE THREAD

**Issue by juhamust** [matt-filion/serverless-external-s3-event#8]
Serverless uses following config keys:
```
functions:
  users:
    handler: users.handler
    events:
      - s3:
          bucket: photos
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
```
(https://serverless.com/framework/docs/providers/aws/events/s3#setting-filter-rules)

Whereas the plugin uses following:
```
functions:
  users:
    handler: users.handler
    events:
      - existingS3:
          bucket: BUCKET_NAME
          bucketEvents: 
            - s3:ObjectCreated:*
          eventRules:
            - prefix: images/
            - suffix: .jpg
```

I strongly suggest using same config keys (eventRules -> event, eventRules -> rules) also in plugin to avoid confusion and errors - unless there is a good reason to do otherwise.
