### ISSUE TITLE
Missing required key 'Events' in params.NotificationConfiguration.LambdaFunctionConfigurations[1]

### ISSUE THREAD

**Issue by s-nt-s** [matt-filion/serverless-external-s3-event#84]
My `serverless.yml` is:

```yalm
plugins:
 - serverless-plugin-existing-s3
service: fire-lamda2
package:
  individually: true
  timeout: 600
  exclude:
    - .svn/**
    - build/**
    - event_*.json
    - sam.bat
    - "*.csv"
    - .project
    - .pydevproject
    - .settings/**
    - .ignoresam
    - Pipfile*
    - requirements.txt
    - template.yml
    - package.yml
    - node_modules/**
provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  stage: Prod
  timeout: 600
  apiName: ${self:service}
  stackName: ${self:service}
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:GetObject"
       Resource: "arn:aws:s3:::forestfires1/*"
    -  Effect: "Allow"
       Action:
         - "es:ESHttpPost"
       Resource: "arn:aws:es:eu-west-1:732803356332:domain/dataia/*"
    -  Effect: "Allow"
       Action:
         - "s3:GetBucketNotification"
         - "s3:PutBucketNotification"
       Resource: "arn:aws:s3:::forestfires1"
layers:
  fireDependenciesLayer:
    path: build
    compatibleRuntimes:
      - python3.6
functions:
  CalcularArea:
    handler: calcular_area.lambda_handler
    name: CalcularArea
    description: API Gateway Fire - CalcularArea
    layers:
      - {Ref: FireDependenciesLayerLambdaLayer } 
    events:
      - http:
          path: calcularArea
          method: post
  CalcularBases:
    handler: calcular_bases.lambda_handler
    name: CalcularBases
    description: API Gateway Fire - CalcularBases
    layers:
      - {Ref: FireDependenciesLayerLambdaLayer } 
    events:
      - http:
          path: calcularBases
          method: get
  CargarDatos:
    handler: cargar_datos.lambda_handler
    name: CargarDatos
    description: API Gateway Fire - CargarDatos
    layers:
      - {Ref: FireDependenciesLayerLambdaLayer } 
    events:
      - existingS3: 
          bucket: forestfires1
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
resources:
  Description: API Gateway Fire
```

and then I execute `sls deploy -v` without any issue, but when I execute `
$ SLS_DEBUG=* sls s3deploy -v --stage Prod` I get:

```console
$ SLS_DEBUG=* sls s3deploy -v --stage Prod
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command s3deploy
Serverless: Invoke s3deploy
Serverless: beforeFunctions --> building ... 
Serverless: beforeFunctions <-- Complete, built 1 events.
Serverless: functions --> prepare to be executed by s3 buckets ... 
Serverless: [AWS lambda 404 0.224s 0 retries] getPolicy({ FunctionName: 'CargarDatos' })
Serverless: [AWS lambda 201 0.208s 0 retries] addPermission({ Action: 'lambda:InvokeFunction',
  FunctionName: 'CargarDatos',
  Principal: 's3.amazonaws.com',
  StatementId: 'exS3-v2-CargarDatos-forestfires1',
  SourceArn: 'arn:aws:s3:::forestfires1' })
Serverless: [AWS lambda 200 0.134s 0 retries] getPolicy({ FunctionName: 'CargarDatos' })
policyId exS3-v2-CargarDatos-forestfires1
Serverless: functions <-- built 0 events across 1 buckets. 
Serverless: beforeS3 --> 
Serverless: [AWS s3 200 0.216s 0 retries] getBucketNotificationConfiguration({ Bucket: 'forestfires1' })
Serverless: beforeS3 <-- 
Serverless: s3 --> initiate requests ...
Serverless: [AWS s3 undefined 0.002s 0 retries] putBucketNotificationConfiguration({ Bucket: 'forestfires1',
  NotificationConfiguration: 
   { TopicConfigurations: [ [length]: 0 ],
     QueueConfigurations: [ [length]: 0 ],
     LambdaFunctionConfigurations: 
      [ { Id: 'e27a566c-b52a-43b2-ad28-8ca5b4f6e4b3',
          LambdaFunctionArn: 'arn:aws:lambda:eu-west-1:732803356332:function:CargarDatos',
          Events: [ 's3:ObjectCreated:*', [length]: 1 ],
          Filter: 
           { Key: 
              { FilterRules: [ { Name: 'Suffix', Value: '.csv' }, [length]: 1 ] } } },
        { Id: 'exS3-v2--1e92d25cf126c4fc268fbe1a3224723d',
          LambdaFunctionArn: 'arn:aws:lambda:eu-west-1:732803356332:function:CargarDatos',
          Events: undefined,
          Filter: 
           { Key: 
              { FilterRules: [ { Name: 'suffix', Value: '.csv' }, [length]: 1 ] } } },
        [length]: 2 ] } })
 
  Error --------------------------------------------------
 
  forestfires1 Missing required key 'Events' in params.NotificationConfiguration.LambdaFunctionConfigurations[1]
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: forestfires1 Missing required key 'Events' in params.NotificationConfiguration.LambdaFunctionConfigurations[1]
    at module.exports.logError (/usr/local/lib/node_modules/serverless/lib/classes/Error.js:92:11)
    at initializeErrorReporter.then.catch.e (/usr/local/lib/node_modules/serverless/bin/serverless:66:3)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at /usr/local/lib/node_modules/serverless/bin/serverless:64:9
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:67:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.10.0
     Serverless Version:     1.38.0
```

But surprisingly the event have been created, as you can see here:

![imagen](https://user-images.githubusercontent.com/5998601/53963844-5d1bae00-40ee-11e9-8c32-875ecf607d2b.png)

or exporting to a `aws sam` file:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: API Gateway Fire - CargarDatos
Resources:
  CargarDatos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: cargar_datos.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: API Gateway Fire - CargarDatos
      MemorySize: 1024
      Timeout: 600
      Role: 'arn:aws:iam::732803356332:role/fire-lamda2-Prod-eu-west-1-lambdaRole'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv
      Tags:
        STAGE: Prod
      Layers:
        - 'arn:aws:lambda:eu-west-1:732803356332:layer:fireDependenciesLayer:27'
  Bucket1:
    Type: 'AWS::S3::Bucket'
```

So, why `sls s3deploy` give me a error.

**Comment by mpfeil** [comment]
Hi @s-nt-s,

I had the same issue because I was not paying attention to the docs/examples.
You have to change *event* to *event***s** under your `existingS3` definition.

```
events:
      - existingS3: 
          bucket: forestfires1
          events: 
            - s3:ObjectCreated:*
          rules:
            - suffix: .csv
```

After that change it was working.
