### ISSUE TITLE
The statement id (exS3-v2-xxx) provided already exists. Please provide a new statement id, or remove the existing statement.

### ISSUE THREAD

**Issue by farbodsalimi** [matt-filion/serverless-external-s3-event#86]
I have one function with two events, prefixes are the same, but suffixes are different:

```yml
 events:
      - existingS3:
          bucket: 'my-bucket'
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: original/
            - suffix: .docx
      - existingS3:
          bucket: 'my-bucket'
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: original/
            - suffix: .txt
```

After running `sls s3deploy` I get this error:
```
The statement id (exS3-v2-xxx) provided already exists. Please provide a new statement id, or remove the existing statement.

Your Environment Information -----------------------------
 OS: linux
 Node Version: 10.14.2
 Serverless Version: 1.38.0
```

I'm not sure if your plugin supports this scenario or not.

**Comment by VadimKhismatov** [comment]
Same problem.
``` yml
iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetBucketNotification'
        - 's3:PutBucketNotification'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::bucket-name'
```
```yml
events:
      - existingS3:
          bucket: name
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: some/
            - suffix: .zip
      - existingS3:
          bucket: name
          events:
            - s3:ObjectRemoved:*
          rules:
            - prefix: some/
            - suffix: .zip
```
```
  The statement id (exS3-v2-stage-bucket-name-bucket-name) provided already exists. Please provide a new statement id, or remove the existing statement.
```
Serverless Version: 1.36.0
Node:  8.14.0

**Comment by dfinlay** [comment]
Same issue, but with a different permutation on second execution.
```
    events:
      - existingS3:
          bucket: 'my-magical-bucket'
          events:
            - s3:ObjectCreated:*
          rules:
            - suffix: .txt
      - existingS3:
          bucket: 'my-magical-bucket'
          events:
            - s3:ObjectCreated:*
          rules:
            - suffix: .log
```
First Error:
```
The statement id (exS3-v2-xxx) provided already exists. Please provide a new statement id, or remove the existing statement.
```
Second Error:
```
<bucket> Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.
```
Multiple suffices doesn't work either:
```
    events:
      - existingS3:
          bucket: 'my-magical-bucket'
          events:
            - s3:ObjectCreated:*
          rules:
            - suffix: .txt
            - suffix: .log
```
Error:
```
<bucket> Cannot specify more than one suffix rule in a filter.
```

Version Info:
```
  Your Environment Information ---------------------------
     OS:                     darwin
     Node Version:           11.14.0
     Serverless Version:     1.40.0
```

**Comment by laneschmidt** [comment]
I'm having this issue too, here's my YAML:

```
events:
    - existingS3:
          bucket: the-chumiest-bucket
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: input1/
            - suffix: .pdf
    - existingS3:
          bucket: the-chumiest-bucket
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: input2/
            - suffix: .pdf
```
