### ISSUE TITLE
TypeError: bucketName.replace is not a function

### ISSUE THREAD

**Issue by mkondel** [matt-filion/serverless-external-s3-event#91]
```yaml
functions:
  imageWatermark: 
    handler: lambdas/watermark.imageWatermark
    events:
      - existingS3:
          bucket:
            Ref: AttachmentsBucket
          events:
            - s3:ObjectCreated:Copy
```
Using `Ref` causes the above error. I know the syntax should work because I use it to expose the dynamic bucket name as an env var in my stack. When using a hardcoded S3 bucket name instead of the `Ref`, the lambda does get assigned.

#66 was closed, but the same problem still persists. I am using `serverless-external-s3-event` v2.3.3.
