### ISSUE TITLE
Missing required key 'Events' 

### ISSUE THREAD

**Issue by matteobattista** [matt-filion/serverless-external-s3-event#93]
Hi,
I have `Missing required key 'Events' ...` when try to run `sls s3deploy...`

This is my configuration:
```
provider:
  name: aws
  runtime: nodejs8.10
```
The plugin is correctly added to `plugins` and in `customs` I have: 

```
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetBucketNotification
        - s3:PutBucketNotification
      Resource: arn:aws:s3:::${self:provider.environment.S3_BUCKET_ASSETS_NAME}
```
My function is: 

```
  assetsLog:
    handler: src/functions/assets/log.handler
    name: ${self:service}-assets-log
    events:
      - existingS3:
          bucket: ${self:provider.environment.S3_BUCKET_ASSETS_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: src/
            - suffix: .txt
```
No problems with `sls deploy`...

I need to run `s3deploy` with `--aws-profile` param like that:
`sls s3deploy --aws-profile xxxxx --verbose`

So the error is:

```
$ sls s3deploy --aws-profile xxxxx --verbose                                             
Serverless: beforeFunctions --> building ... 
Serverless: beforeFunctions <-- Complete, built 1 events.
Serverless: functions --> prepare to be executed by s3 buckets ... 
policyId exS3-v2-[name]-dashboard-sls-assets-log-[name]-dashboard-sls-assets-dev
Serverless: functions <-- built 0 events across 1 buckets. 
Serverless: beforeS3 --> 
Serverless: beforeS3 <-- 
Serverless: s3 --> initiate requests ...
Unhandled rejection Error: [name]-dashboard-sls-assets-dev Missing required key 'Events' in params.NotificationConfiguration.LambdaFunctionConfigurations[0]
    at module.exports.logError (/usr/local/lib/node_modules/serverless/lib/classes/Error.js:92:11)
    at initializeErrorReporter.then.catch.e (/usr/local/lib/node_modules/serverless/bin/serverless:64:3)
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:690:18)
    at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
    at process.topLevelDomainCallback (domain.js:120:23)
```

Thank you in advance!
